export enum HttpStatusCode {

  OK = 200,
  CREATED = 201,
  ACCEPTED = 202,
  NO_CONTENT = 204,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  METHOD_NOT_ALLOWED = 405,
  CONFLICT = 409,
  UNPROCESSABLE_ENTITY = 422,
  TOO_MANY_REQUESTS = 429,
  INTERNAL_SERVER_ERROR = 500,
  NOT_IMPLEMENTED = 501,
  BAD_GATEWAY = 502,
  SERVICE_UNAVAILABLE = 503,
  GATEWAY_TIMEOUT = 504
}

export enum AuthStatusCode {
  LOGIN_SUCCESS = HttpStatusCode.OK,
  REGISTRATION_SUCCESS = HttpStatusCode.CREATED,
  LOGOUT_SUCCESS = HttpStatusCode.OK,
  TOKEN_REFRESH_SUCCESS = HttpStatusCode.OK,
  
  INVALID_CREDENTIALS = HttpStatusCode.UNAUTHORIZED,
  TOKEN_EXPIRED = HttpStatusCode.UNAUTHORIZED,
  TOKEN_INVALID = HttpStatusCode.UNAUTHORIZED,
  NO_TOKEN_PROVIDED = HttpStatusCode.UNAUTHORIZED,
  
  INSUFFICIENT_PERMISSIONS = HttpStatusCode.FORBIDDEN,
  ACCOUNT_BLOCKED = HttpStatusCode.FORBIDDEN,
  ACCOUNT_NOT_VERIFIED = HttpStatusCode.FORBIDDEN,
  
  EMAIL_ALREADY_EXISTS = HttpStatusCode.CONFLICT,
  USERNAME_ALREADY_EXISTS = HttpStatusCode.CONFLICT,
  
  OTP_EXPIRED = HttpStatusCode.BAD_REQUEST,
  OTP_INVALID = HttpStatusCode.BAD_REQUEST,
  PASSWORD_TOO_WEAK = HttpStatusCode.BAD_REQUEST
}

export enum ValidationStatusCode {
  VALIDATION_ERROR = HttpStatusCode.BAD_REQUEST,
  MISSING_REQUIRED_FIELDS = HttpStatusCode.BAD_REQUEST,
  INVALID_EMAIL_FORMAT = HttpStatusCode.UNPROCESSABLE_ENTITY,
  INVALID_PHONE_FORMAT = HttpStatusCode.UNPROCESSABLE_ENTITY,
  INVALID_DATE_FORMAT = HttpStatusCode.UNPROCESSABLE_ENTITY,
  FIELD_TOO_LONG = HttpStatusCode.UNPROCESSABLE_ENTITY,
  FIELD_TOO_SHORT = HttpStatusCode.UNPROCESSABLE_ENTITY
}

export enum ProfileStatusCode {
  PROFILE_CREATED = HttpStatusCode.CREATED,
  PROFILE_UPDATED = HttpStatusCode.OK,
  PROFILE_DELETED = HttpStatusCode.OK,
  PROFILE_NOT_FOUND = HttpStatusCode.NOT_FOUND,
  PROFILE_ALREADY_EXISTS = HttpStatusCode.CONFLICT,
  
  EXPERIENCE_ADDED = HttpStatusCode.CREATED,
  EXPERIENCE_UPDATED = HttpStatusCode.OK,
  EXPERIENCE_DELETED = HttpStatusCode.OK,
  EXPERIENCE_NOT_FOUND = HttpStatusCode.NOT_FOUND,
  
  EDUCATION_ADDED = HttpStatusCode.CREATED,
  EDUCATION_UPDATED = HttpStatusCode.OK,
  EDUCATION_DELETED = HttpStatusCode.OK,
  EDUCATION_NOT_FOUND = HttpStatusCode.NOT_FOUND
}
