export enum HttpStatusCode {
  OK = 200,
  CREATED = 201,
  ACCEPTED = 202,
  NO_CONTENT = 204,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  METHOD_NOT_ALLOWED = 405,
  CONFLICT = 409,
  UNPROCESSABLE_ENTITY = 422,
  TOO_MANY_REQUESTS = 429,
  INTERNAL_SERVER_ERROR = 500,
  NOT_IMPLEMENTED = 501,
  BAD_GATEWAY = 502,
  SERVICE_UNAVAILABLE = 503,
  GATEWAY_TIMEOUT = 504
}

export enum AuthStatusCode {
  LOGIN_SUCCESS = HttpStatusCode.OK,
  REGISTRATION_SUCCESS = HttpStatusCode.CREATED,
  INVALID_CREDENTIALS = HttpStatusCode.UNAUTHORIZED,
  EMAIL_ALREADY_EXISTS = HttpStatusCode.CONFLICT,
  OTP_EXPIRED = HttpStatusCode.BAD_REQUEST,
  ACCOUNT_BLOCKED = HttpStatusCode.FORBIDDEN
}

export enum ValidationStatusCode {
  VALIDATION_ERROR = HttpStatusCode.BAD_REQUEST,
  MISSING_REQUIRED_FIELDS = HttpStatusCode.BAD_REQUEST,
  INVALID_FORMAT = HttpStatusCode.UNPROCESSABLE_ENTITY
}
