import 'reflect-metadata';
import { Container } from 'inversify';
import TYPES from './types';
import { UserService } from '../services/UserService';
import { UserRepository } from '../repositories/UserRepository';
import { EmailService } from '../services/EmailService';
import { RedisService } from '../services/RedisService';
import { UserController } from '../controllers/UserController';
import { AdminRepository } from '../repositories/AdminRepository';
import { AdminService } from '../services/AdminService';
import { AdminController } from '../controllers/AdminController';
import { IUserRepository } from '../repositories/IUserRepository';
import { IAdminRepository } from '../repositories/IAdminRepository';
import { IAdminService } from '../services/IAdminService';
import { IUserService } from '../services/IUserService';
import { ProfileRepository } from '../repositories/ProfileRepository';
import { IProfileRepository } from '../repositories/IProfileRepository';
import { ProfileService } from '../services/ProfileService';
import { IProfileService } from '../services/IProfileService';
import { ProfileController } from '../controllers/ProfileController';
import { CompanyApiRepository, ICompanyApiRepository } from '../repositories/CompanyApiRepository';
import { JWTService } from '../services/JWTService';
import { ResumeController } from '../controllers/ResumeController';
import { ResumeService } from '../services/ResumeService';
import { ResumeRepository } from '../repositories/ResumeRepository';
import { IResumeRepository } from '../repositories/IResumeRepository';
import { IResumeService } from '../services/IResumeService';
import { ICertificationRepository } from '../repositories/ICertificationRepository';
import { ICertificationService } from '../services/ICertificationService';
import { CertificationController } from '../controllers/CertificationController';
import { CertificationService } from '../services/CertificationService';
import { CertificationRepository } from '../repositories/CertificationRepository';
import { IAchievementRepository } from '../repositories/IAchievementRepository';
import { IAchievementService } from '../services/IAchievementService';
import { AchievementController } from '../controllers/AchievementController';
import { AchievementService } from '../services/AchievementService';
import { AchievementRepository } from '../repositories/AchievementRepository';


const container = new Container();

container.bind<UserService>(TYPES.UserService).to(UserService);
container.bind<IUserService>(TYPES.IUserService).to(UserService);
container.bind<IUserRepository>(TYPES.IUserRepository).to(UserRepository);
container.bind<EmailService>(TYPES.EmailService).to(EmailService);
container.bind<RedisService>(TYPES.RedisService).to(RedisService).inSingletonScope();
container.bind<UserController>(TYPES.UserController).to(UserController);
container.bind<AdminRepository>(TYPES.AdminRepository).to(AdminRepository);
container.bind<IAdminRepository>(TYPES.IAdminRepository).to(AdminRepository);
container.bind<AdminService>(TYPES.AdminService).to(AdminService);
container.bind<IAdminService>(TYPES.IAdminService).to(AdminService);
container.bind<AdminController>(TYPES.AdminController).to(AdminController);
container.bind<IProfileRepository>(TYPES.IProfileRepository).to(ProfileRepository);
container.bind<IProfileService>(TYPES.IProfileService).to(ProfileService);
container.bind<ProfileController>(TYPES.ProfileController).to(ProfileController);
container.bind<ICompanyApiRepository>(TYPES.ICompanyApiRepository).to(CompanyApiRepository);
container.bind<JWTService>(TYPES.JWTService).to(JWTService);
container.bind<IResumeRepository>('IResumeRepository').to(ResumeRepository);
container.bind<IResumeService>('IResumeService').to(ResumeService);
container.bind<ResumeController>('ResumeController').to(ResumeController);
container.bind<ICertificationRepository>('ICertificationRepository').to(CertificationRepository);
container.bind<ICertificationService>('ICertificationService').to(CertificationService);
container.bind<CertificationController>('CertificationController').to(CertificationController);
container.bind<IAchievementRepository>('IAchievementRepository').to(AchievementRepository);
container.bind<IAchievementService>('IAchievementService').to(AchievementService);
container.bind<AchievementController>('AchievementController').to(AchievementController);
export default container;